name: plugin-cron
org: kingsworld
install: true
packagePath: packages/cron
identifierBase: false
pushTag: true
githubRelease: true
githubReleaseLatest: true
gitRepo: Kings-World/sapphire-plugins
gitHostVariant: github
